name: time_track
description: >-
  A simple command-line time tracking application 
  demonstrating usage of Realm Dart SDK

version: 0.2.0
homepage: https://github.com/realm/realm-dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  realm_dart: ^0.3.1+beta
  args: ^2.0.0
  dart_console: ^1.1.0-pre.0

dev_dependencies:
  lints: ^1.0.1
