name: myapp
description: A simple command-line application using Realm Dart SDK.
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  realm_dart: ^0.2.0-alpha.2

dev_dependencies:
  lints: ^1.0.1
